// Code generated by MockGen. DO NOT EDIT.
// Source: ./itemTypes.go
//
// Generated by this command:
//
//	mockgen -source=./itemTypes.go -destination=./mocks/ItemTypesRepo.go -package=mock_repos ItemTypesRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	repos "github.com/happilymarrieddad/old-world/api3/internal/repos"
	types "github.com/happilymarrieddad/old-world/api3/types"
	neo4j "github.com/neo4j/neo4j-go-driver/v5/neo4j"
	gomock "go.uber.org/mock/gomock"
)

// MockItemTypesRepo is a mock of ItemTypesRepo interface.
type MockItemTypesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockItemTypesRepoMockRecorder
}

// MockItemTypesRepoMockRecorder is the mock recorder for MockItemTypesRepo.
type MockItemTypesRepoMockRecorder struct {
	mock *MockItemTypesRepo
}

// NewMockItemTypesRepo creates a new mock instance.
func NewMockItemTypesRepo(ctrl *gomock.Controller) *MockItemTypesRepo {
	mock := &MockItemTypesRepo{ctrl: ctrl}
	mock.recorder = &MockItemTypesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemTypesRepo) EXPECT() *MockItemTypesRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockItemTypesRepo) Find(ctx context.Context, opts *repos.FindItemTypeOpts) ([]*types.ItemType, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].([]*types.ItemType)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockItemTypesRepoMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockItemTypesRepo)(nil).Find), ctx, opts)
}

// FindOrCreate mocks base method.
func (m *MockItemTypesRepo) FindOrCreate(ctx context.Context, at types.CreateItemType) (*types.ItemType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, at)
	ret0, _ := ret[0].(*types.ItemType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockItemTypesRepoMockRecorder) FindOrCreate(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockItemTypesRepo)(nil).FindOrCreate), ctx, at)
}

// Update mocks base method.
func (m *MockItemTypesRepo) Update(ctx context.Context, itmTp types.UpdateItemType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, itmTp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockItemTypesRepoMockRecorder) Update(ctx, itmTp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockItemTypesRepo)(nil).Update), ctx, itmTp)
}

// UpdateTx mocks base method.
func (m *MockItemTypesRepo) UpdateTx(ctx context.Context, tx neo4j.ManagedTransaction, itmTp types.UpdateItemType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, itmTp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockItemTypesRepoMockRecorder) UpdateTx(ctx, tx, itmTp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockItemTypesRepo)(nil).UpdateTx), ctx, tx, itmTp)
}
