// Code generated by MockGen. DO NOT EDIT.
// Source: ./statistics.go
//
// Generated by this command:
//
//	mockgen -source=./statistics.go -destination=./mocks/StatisticsRepo.go -package=mock_repos StatisticsRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	types "github.com/happilymarrieddad/old-world/api3/types"
	gomock "go.uber.org/mock/gomock"
)

// MockStatisticsRepo is a mock of StatisticsRepo interface.
type MockStatisticsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsRepoMockRecorder
}

// MockStatisticsRepoMockRecorder is the mock recorder for MockStatisticsRepo.
type MockStatisticsRepoMockRecorder struct {
	mock *MockStatisticsRepo
}

// NewMockStatisticsRepo creates a new mock instance.
func NewMockStatisticsRepo(ctrl *gomock.Controller) *MockStatisticsRepo {
	mock := &MockStatisticsRepo{ctrl: ctrl}
	mock.recorder = &MockStatisticsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticsRepo) EXPECT() *MockStatisticsRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStatisticsRepo) Find(ctx context.Context, gameID string, limit, offset int) ([]*types.Statistic, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, gameID, limit, offset)
	ret0, _ := ret[0].([]*types.Statistic)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockStatisticsRepoMockRecorder) Find(ctx, gameID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStatisticsRepo)(nil).Find), ctx, gameID, limit, offset)
}

// FindOrCreate mocks base method.
func (m *MockStatisticsRepo) FindOrCreate(ctx context.Context, at types.CreateStatistic) (*types.Statistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, at)
	ret0, _ := ret[0].(*types.Statistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockStatisticsRepoMockRecorder) FindOrCreate(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockStatisticsRepo)(nil).FindOrCreate), ctx, at)
}
