// Code generated by MockGen. DO NOT EDIT.
// Source: ./troopTypes.go
//
// Generated by this command:
//
//	mockgen -source=./troopTypes.go -destination=./mocks/TroopTypesRepo.go -package=mock_repos TroopTypesRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	types "github.com/happilymarrieddad/old-world/api3/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTroopTypesRepo is a mock of TroopTypesRepo interface.
type MockTroopTypesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTroopTypesRepoMockRecorder
}

// MockTroopTypesRepoMockRecorder is the mock recorder for MockTroopTypesRepo.
type MockTroopTypesRepoMockRecorder struct {
	mock *MockTroopTypesRepo
}

// NewMockTroopTypesRepo creates a new mock instance.
func NewMockTroopTypesRepo(ctrl *gomock.Controller) *MockTroopTypesRepo {
	mock := &MockTroopTypesRepo{ctrl: ctrl}
	mock.recorder = &MockTroopTypesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTroopTypesRepo) EXPECT() *MockTroopTypesRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockTroopTypesRepo) Find(ctx context.Context, gameID string, limit, offset int) ([]*types.TroopType, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, gameID, limit, offset)
	ret0, _ := ret[0].([]*types.TroopType)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockTroopTypesRepoMockRecorder) Find(ctx, gameID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTroopTypesRepo)(nil).Find), ctx, gameID, limit, offset)
}

// FindOrCreate mocks base method.
func (m *MockTroopTypesRepo) FindOrCreate(ctx context.Context, at types.CreateTroopType) (*types.TroopType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, at)
	ret0, _ := ret[0].(*types.TroopType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockTroopTypesRepoMockRecorder) FindOrCreate(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockTroopTypesRepo)(nil).FindOrCreate), ctx, at)
}
