// Code generated by MockGen. DO NOT EDIT.
// Source: ./unitOptionTypes.go
//
// Generated by this command:
//
//	mockgen -source=./unitOptionTypes.go -destination=./mocks/UnitOptionTypesRepo.go -package=mock_repos UnitOptionTypesRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	types "github.com/happilymarrieddad/old-world/api3/types"
	neo4j "github.com/neo4j/neo4j-go-driver/v5/neo4j"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOptionTypesRepo is a mock of UnitOptionTypesRepo interface.
type MockUnitOptionTypesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOptionTypesRepoMockRecorder
}

// MockUnitOptionTypesRepoMockRecorder is the mock recorder for MockUnitOptionTypesRepo.
type MockUnitOptionTypesRepoMockRecorder struct {
	mock *MockUnitOptionTypesRepo
}

// NewMockUnitOptionTypesRepo creates a new mock instance.
func NewMockUnitOptionTypesRepo(ctrl *gomock.Controller) *MockUnitOptionTypesRepo {
	mock := &MockUnitOptionTypesRepo{ctrl: ctrl}
	mock.recorder = &MockUnitOptionTypesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOptionTypesRepo) EXPECT() *MockUnitOptionTypesRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockUnitOptionTypesRepo) Find(ctx context.Context, gameID string, limit, offset int) ([]*types.UnitOptionType, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, gameID, limit, offset)
	ret0, _ := ret[0].([]*types.UnitOptionType)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockUnitOptionTypesRepoMockRecorder) Find(ctx, gameID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUnitOptionTypesRepo)(nil).Find), ctx, gameID, limit, offset)
}

// FindOrCreate mocks base method.
func (m *MockUnitOptionTypesRepo) FindOrCreate(ctx context.Context, at types.CreateUnitOptionType) (*types.UnitOptionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, at)
	ret0, _ := ret[0].(*types.UnitOptionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockUnitOptionTypesRepoMockRecorder) FindOrCreate(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockUnitOptionTypesRepo)(nil).FindOrCreate), ctx, at)
}

// FindOrCreateTx mocks base method.
func (m *MockUnitOptionTypesRepo) FindOrCreateTx(ctx context.Context, tx neo4j.ManagedTransaction, at types.CreateUnitOptionType) (*types.UnitOptionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateTx", ctx, tx, at)
	ret0, _ := ret[0].(*types.UnitOptionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateTx indicates an expected call of FindOrCreateTx.
func (mr *MockUnitOptionTypesRepoMockRecorder) FindOrCreateTx(ctx, tx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateTx", reflect.TypeOf((*MockUnitOptionTypesRepo)(nil).FindOrCreateTx), ctx, tx, at)
}

// Update mocks base method.
func (m *MockUnitOptionTypesRepo) Update(ctx context.Context, uot types.UpdateUnitOptionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, uot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUnitOptionTypesRepoMockRecorder) Update(ctx, uot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUnitOptionTypesRepo)(nil).Update), ctx, uot)
}

// UpdateTx mocks base method.
func (m *MockUnitOptionTypesRepo) UpdateTx(ctx context.Context, tx neo4j.ManagedTransaction, uot types.UpdateUnitOptionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, uot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockUnitOptionTypesRepoMockRecorder) UpdateTx(ctx, tx, uot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockUnitOptionTypesRepo)(nil).UpdateTx), ctx, tx, uot)
}
